name: 'wald_stack'
version: '1.0.0'
require-dbt-version: '>=1.3.0'
config-version: 2
profile: 'default'

model-paths:
  - 'models'
analysis-paths:
  - 'analyses'
test-paths:
  - 'tests'
seed-paths:
  - 'seeds'
macro-paths:
  - 'macros'
snapshot-paths:
  - 'snapshots'
target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  wald_stack:
    +database: MY_DB
    staging:
      +docs:
        node_color: "CadetBlue"

    intermediate:
      +docs:
        node_color: "MediumSlateBlue"

    marts:
      +materialized: table
      aggregates:
        +docs:
          node_color: "Maroon"
        +tags: "bi"
      core:
        +docs:
          node_color: "#800080"
      ml:
        prep:
          +docs:
            node_color: "Indigo"
        train_predict:
          +docs:
            node_color: "#36454f"
