name: wald-stack
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - jupyterlab
  - dbt-core
  - dbt-snowflake
  - snowflake-snowpark-python
  - snowflake-connector-python
  - pre-commit
  - black
  - flake8
  - isort
