# Hatch is only used for managing the default environment
# This file is only needed if you want to use Hatch instead of mamba to manage your environment
# Also consider installing pyenv to install Python 3.8 which is needed by Snowflake

[project]
requires-python = "~=3.8"
name = "wald-stack-demo"
description = "Demonstrating the WALD-stack on Snowflake"
readme = "README.md"
license = { text = "MIT" }
keywords = [
  "dbt",
  "snowflake",
  "python",
  "snowpark",
]
authors = [
  { name = "Florian Wilhelm", email = "Florian.Wilhelm@gmail.com" },
]

[envs.default]
python = "3.8"
dependencies = [
  "dbt-core",
  "dbt-snowflake",
  "jupyterlab",
  "snowflake-snowpark-python[pandas]",
  "snowflake-connector-python[pandas]",
]
[envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=src/hatch_showcase --cov=tests"
no-cov = "cov --no-cov"
